const { Pool } = require('pg');
const { normalizePlaceholders } = require('../utils/sql');

let pool = null;
let db = null;
let initialized = false;

const getConnectionString = () =>
  process.env.DATABASE_URL || process.env.POSTGRES_URL || process.env.NEON_DATABASE_URL || '';

const createPool = () => {
  const connectionString = getConnectionString();

  if (!connectionString) {
    throw new Error('DATABASE_URL is required for Postgres');
  }

  return new Pool({
    connectionString,
    ssl: connectionString.includes('localhost')
      ? false
      : { rejectUnauthorized: false }
  });
};

const createDbAdapter = (pgPool) => ({
  async query(query, params = []) {
    return pgPool.query(normalizePlaceholders(query), params);
  },

  async run(query, params = []) {
    return pgPool.query(normalizePlaceholders(query), params);
  },

  async exec(query, params = []) {
    const result = await pgPool.query(normalizePlaceholders(query), params);

    if (!result.rows.length) {
      return [];
    }

    const columns = result.fields.map((field) => field.name);
    const values = result.rows.map((row) => columns.map((column) => row[column]));

    return [{ columns, values }];
  }
});

async function getDB() {
  if (db) return db;

  pool = createPool();
  db = createDbAdapter(pool);

  if (!initialized) {
    await ensureTablesExist(pool);
    initialized = true;
  }

  return db;
}

async function ensureTablesExist(database) {
  await createTables(database);
  await ensureColumnsExist(database);
}

async function createTables(database) {
  await database.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL CHECK (role IN ('admin', 'employee')),
      first_name TEXT NOT NULL,
      last_name TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_users_role ON users(role)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS employee_profiles (
      user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      department TEXT,
      position TEXT,
      hire_date DATE,
      manager_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      avatar_url TEXT,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await database.query(`
    CREATE TABLE IF NOT EXISTS tasks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT,
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
      priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
      assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
      due_date DATE,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee_id)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS task_assignments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(task_id, user_id)
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_task_assignments_task ON task_assignments(task_id)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_task_assignments_user ON task_assignments(user_id)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS comments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      content TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_comments_task ON comments(task_id)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      message TEXT NOT NULL,
      type TEXT NOT NULL DEFAULT 'info',
      is_read INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(is_read)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS time_entries (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      start_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      end_time TIMESTAMPTZ,
      duration_minutes INTEGER DEFAULT 0,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_time_entries_task ON time_entries(task_id)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_time_entries_user ON time_entries(user_id)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_time_entries_active ON time_entries(user_id, end_time)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS attendance_records (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      attendance_date DATE NOT NULL,
      check_in_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      check_out_time TIMESTAMPTZ,
      total_minutes INTEGER DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'present' CHECK (status IN ('present', 'late')),
      work_summary TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, attendance_date)
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_attendance_user_date ON attendance_records(user_id, attendance_date)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance_records(attendance_date)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS gamification_profiles (
      user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      total_points INTEGER NOT NULL DEFAULT 0,
      current_streak INTEGER NOT NULL DEFAULT 0,
      longest_streak INTEGER NOT NULL DEFAULT 0,
      last_activity_date DATE,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await database.query(`
    CREATE TABLE IF NOT EXISTS gamification_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      event_type TEXT NOT NULL,
      points INTEGER NOT NULL,
      reference_type TEXT,
      reference_id INTEGER,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, event_type, reference_type, reference_id)
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_gamification_events_user ON gamification_events(user_id)`);
  await database.query(`CREATE INDEX IF NOT EXISTS idx_gamification_events_created_at ON gamification_events(created_at)`);

  await database.query(`
    CREATE TABLE IF NOT EXISTS user_badges (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      badge_key TEXT NOT NULL,
      badge_name TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, badge_key)
    )
  `);

  await database.query(`CREATE INDEX IF NOT EXISTS idx_user_badges_user ON user_badges(user_id)`);
}

async function ensureColumnsExist(database) {
  await database.query(`ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS work_summary TEXT`);
  await database.query(`
    ALTER TABLE task_assignments
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending'
  `);
  await database.query(`
    ALTER TABLE task_assignments
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
  `);
  await database.query(`
    INSERT INTO task_assignments (task_id, user_id)
    SELECT t.id, t.assignee_id
    FROM tasks t
    WHERE t.assignee_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM task_assignments ta
        WHERE ta.task_id = t.id
          AND ta.user_id = t.assignee_id
      )
  `);
  await database.query(`
    UPDATE task_assignments ta
    SET status = t.status,
        updated_at = CURRENT_TIMESTAMP
    FROM tasks t
    WHERE ta.task_id = t.id
      AND (ta.status IS NULL OR ta.status = 'pending')
  `);
}

async function saveDB() {
  return Promise.resolve();
}

module.exports = { getDB, saveDB };
